#! /bin/bash
# author : lordpax
# passphrase v1.0
# Petit script permettant de générer des passphrases aléatoirement

dict="/usr/share/hunspell/fr_FR.dic"
nbLine=$(wc -l < $dict)
nbWord=1
maxLength=0
version="v1.0"

function helpFunc() {
    echo "Usage : $0 [options]

Option :
-h or --help ...................... This help
-v or --version ................... Show version
-n <nbWord> ....................... Number of word 
-l <length> ....................... Max length of word (soon)
-w <file> ......................... Wordlist
-s ................................ Statistiques (soon)"
    exit 0
}

function genWord() {
    local random=$(shuf -i 1-$nbLine -n 1)

    local word=$(head -n $random $dict | tail -1)
    word=$(echo $word | cut -d '/' -f 1)
    word=$(echo $word | awk '{print $1}')

    echo $word
}

function genPassphrase() {
    local pass=""

    for i in $(seq 1 $nbWord); do
        pass="$pass $(genWord)"
    done

    echo $pass
}

if [ $# -ge 1 ]; then
    for i in $(seq 1 $#); do
        if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then 
            helpFunc
        elif [ "$1" == "--version" ] || [ "$1" == "-v" ]; then 
            echo $version
            exit
        elif [ "$1" == "-n" ]; then 
            shift
            nbWord=$1
        elif [ "$1" == "-l" ]; then 
            shift
            maxLength=$1
        elif [ "$1" == "-w" ]; then 
            shift
            dict=$1
            nbLine=$(wc -l < $1)
        fi
        shift
    done
fi

genPassphrase
