#!/bin/bash
# author : lordpax
# passphrase v1.1.0
# Petit script permettant de générer des passphrases aléatoirement

dict="/usr/share/hunspell/fr_FR.dic"
nbLine=$(grep -E "^[a-zA-Z0-9]+/" $dict | wc -l)
nbWord=1
maxLength=0
version="v1.1.0"

function helpFunc() {
    echo "Usage : $0 [options]

Option :
-h or --help ...................... This help
-v or --version ................... Show version
-n <nbWord> ....................... Number of word 
-l <length> ....................... Max length of word
-w <file> ......................... Wordlist
-s ................................ Statistiques (soon)"
    exit 0
}

# genWord <wordLength>
function genWord() {
    if [ $1 -gt 0 ]; then
        nbLine=$(grep -E "^[a-zA-Z0-9]{1,$1}/" $dict | wc -l)
    fi

    local random=$(shuf -i 1-$nbLine -n 1)
    local word=""

    if [ $1 -gt 0 ]; then
        word=$(grep -E "^[a-zA-Z0-9]{1,$1}/" $dict | head -n $random | tail -1)
    else
        word=$(grep -E "^[a-zA-Z0-9]+/" $dict | head -n $random | tail -1)
    fi

    word=$(echo $word | cut -d '/' -f 1)
    word=$(echo $word | awk '{print $1}')

    echo $word
}

function genPassphrase() {
    local pass=""

    for i in $(seq 1 $nbWord); do
        pass="$pass $(genWord $maxLength)"
    done

    echo $pass
}

if [ $# -ge 1 ]; then
    for i in $(seq 1 $#); do
        if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then 
            helpFunc
        elif [ "$1" == "--version" ] || [ "$1" == "-v" ]; then 
            echo $version
            exit
        elif [ "$1" == "-n" ]; then 
            shift
            nbWord=$1
        elif [ "$1" == "-l" ]; then 
            shift
            maxLength=$1
        elif [ "$1" == "-w" ]; then 
            shift
            dict=$1
            nbLine=$(wc -l < $1)
        fi
        shift
    done
fi

genPassphrase
